<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Mecaviv.Infrastructure</RootNamespace>
    <AssemblyName>mecaviv-infrastructure</AssemblyName>
    <NoWarn>$(NoWarn);NU1510;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Compile Include="Logging.fs" />
    <Compile Include="WebHost.fs" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
