<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SirenManager.Web</RootNamespace>
    <AssemblyName>sirenmanager-web</AssemblyName>
    <NoWarn>$(NoWarn);NU1510;</NoWarn>
    <DefaultItemExcludes>$(DefaultItemExcludes);node_modules/**;**/*.wasm</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.fsproj" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
