<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SirenManager.Backend</RootNamespace>
    <AssemblyName>sirenmanager-backend</AssemblyName>
      <NoWarn>$(NoWarn);NU1510;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Infrastructure.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Config.fs" />
    <Compile Include="SshProxy.fs" />
    <Compile Include="Protocol.fs" />
    <Compile Include="Midi.fs" />
    <Compile Include="MidiCache.fs" />
    <Compile Include="MidiScan.fs" />
    <Compile Include="Sim.fs" />
    <Compile Include="Scheduler.fs" />
    <Compile Include="UdpRelay.fs" />
    <Compile Include="Api.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>